name: Release
on:
  push:
    tags:
      - 'v*.*.*'

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13.1
      uses: actions/setup-go@v1
      with:
        go-version: 1.13.1
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: go get -v -t -d ./...

    - name: Build linux-amd64
      run: GOOS=linux GOARCH=amd64 go build -v -trimpath -ldflags "-X main.version=`git describe --tags --always --dirty`" -o sobbs.linux-amd64
    - name: Build linux-386
      run: GOOS=linux GOARCH=386 go build -v -trimpath -ldflags "-X main.version=`git describe --tags --always --dirty`" -o sobbs.linux-386
    - name: Build darwin-amd64
      run: GOOS=darwin GOARCH=amd64 go build -v -trimpath -ldflags "-X main.version=`git describe --tags --always --dirty`" -o sobbs.darwin-amd64
    - name: Build darwin-386
      run: GOOS=darwin GOARCH=386 go build -v -trimpath -ldflags "-X main.version=`git describe --tags --always --dirty`" -o sobbs.darwin-386
    - name: Build windows-amd64
      run: GOOS=darwin GOARCH=386 go build -v -trimpath -ldflags "-X main.version=`git describe --tags --always --dirty`" -o sobbs.windows-amd64.exe
    - name: Build windows-386
      run: GOOS=darwin GOARCH=386 go build -v -trimpath -ldflags "-X main.version=`git describe --tags --always --dirty`" -o sobbs.windows-386.exe

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
          files: |
            sobbs.linux-amd64
            sobbs.linux-386
            sobbs.darwin-amd64
            sobbs.darwin-386
            sobbs.windows-amd64.exe
            sobbs.windows-386.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
